### ISSUE TITLE
Errors in evaluated script can crash server

### ISSUE THREAD

**Issue by RobWunderlich** [miralemd/qlik-sse#1]
Error in the code evaluated by ScriptEval() will cause the server instance to terminate with the uncaught error.  For example:
`x.find()`
where x is undefined of find() is not a method.

I've fixed this by adding try/catch here: https://github.com/RobWunderlich/qlik-sse/commit/91408d478ce4a153c7cdca3ba07dd96d32a7c1a8

Ideally, the value returned to Qlik would be a Qlik null, not the string "null" or "undefined".  Is there some `sse.DataType` for null?

**Comment by miralemd** [comment]
@RobWunderlich I've added some error handling as per your suggestion, and added an additional check when parsing the script to make sure invalid javascript doesn't crash the server.

fixed by https://github.com/miralemd/qlik-sse/commit/8ec5dd4e51927eae9a5911f03f714f8a88321179

**Comment by miralemd** [comment]
Oh, with regards to `null` there is  no such type in the `.proto` defined, so for now it's either an empty string or NaN for numbers
